Refactor traefik with package
Split a bit traefik into package. The idea behind this refactor is to
start move inter-dependencies away and do some DRY or SRP.

- Adds a `provider` package, with providers except `web.go`
- Adds a `types` package with common struct.
- Move `gen.go` to an `autogen` package

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

diff --git a/script/crossbinary b/script/crossbinary
--- a/script/crossbinary
+++ b/script/crossbinary
@@ -1,8 +1,8 @@
 #!/bin/bash
 set -e
 
-if ! test -e gen.go; then
-	echo >&2 'error: generate must be run before binary'
+if ! test -e autogen/gen.go; then
+	echo >&2 'error: generate must be run before crossbinary'
 	false
 fi
 
